<?php

/**
 * BaseTool
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $code
 * @property string $name
 * @property string $url
 * @property blob $description
 * @property Doctrine_Collection $Projects
 * @property Doctrine_Collection $ProjectTools
 * @property Guide $Guide
 * 
 * @method integer             getId()           Returns the current record's "id" value
 * @method string              getCode()         Returns the current record's "code" value
 * @method string              getName()         Returns the current record's "name" value
 * @method string              getUrl()          Returns the current record's "url" value
 * @method blob                getDescription()  Returns the current record's "description" value
 * @method Doctrine_Collection getProjects()     Returns the current record's "Projects" collection
 * @method Doctrine_Collection getProjectTools() Returns the current record's "ProjectTools" collection
 * @method Guide               getGuide()        Returns the current record's "Guide" value
 * @method Tool                setId()           Sets the current record's "id" value
 * @method Tool                setCode()         Sets the current record's "code" value
 * @method Tool                setName()         Sets the current record's "name" value
 * @method Tool                setUrl()          Sets the current record's "url" value
 * @method Tool                setDescription()  Sets the current record's "description" value
 * @method Tool                setProjects()     Sets the current record's "Projects" collection
 * @method Tool                setProjectTools() Sets the current record's "ProjectTools" collection
 * @method Tool                setGuide()        Sets the current record's "Guide" value
 * 
 * @package    sitioCalidad
 * @subpackage model
 * @author     Fernando G. Panci
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTool extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tool');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('code', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('url', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('description', 'blob', null, array(
             'type' => 'blob',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Project as Projects', array(
             'refClass' => 'ProjectTool',
             'local' => 'tool_id',
             'foreign' => 'project_id'));

        $this->hasMany('ProjectTool as ProjectTools', array(
             'local' => 'id',
             'foreign' => 'tool_id'));

        $this->hasOne('Guide', array(
             'local' => 'id',
             'foreign' => 'tool_id'));
    }
}