<?php

/**
 * BaseProject
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $url
 * @property blob $description
 * @property integer $company_id
 * @property Company $Company
 * @property Doctrine_Collection $Tools
 * @property Doctrine_Collection $ProjectTools
 * 
 * @method integer             getId()           Returns the current record's "id" value
 * @method string              getName()         Returns the current record's "name" value
 * @method string              getUrl()          Returns the current record's "url" value
 * @method blob                getDescription()  Returns the current record's "description" value
 * @method integer             getCompanyId()    Returns the current record's "company_id" value
 * @method Company             getCompany()      Returns the current record's "Company" value
 * @method Doctrine_Collection getTools()        Returns the current record's "Tools" collection
 * @method Doctrine_Collection getProjectTools() Returns the current record's "ProjectTools" collection
 * @method Project             setId()           Sets the current record's "id" value
 * @method Project             setName()         Sets the current record's "name" value
 * @method Project             setUrl()          Sets the current record's "url" value
 * @method Project             setDescription()  Sets the current record's "description" value
 * @method Project             setCompanyId()    Sets the current record's "company_id" value
 * @method Project             setCompany()      Sets the current record's "Company" value
 * @method Project             setTools()        Sets the current record's "Tools" collection
 * @method Project             setProjectTools() Sets the current record's "ProjectTools" collection
 * 
 * @package    sitioCalidad
 * @subpackage model
 * @author     Fernando G. Panci
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProject extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('project');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('url', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('description', 'blob', null, array(
             'type' => 'blob',
             ));
        $this->hasColumn('company_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Company', array(
             'local' => 'company_id',
             'foreign' => 'id'));

        $this->hasMany('Tool as Tools', array(
             'refClass' => 'ProjectTool',
             'local' => 'project_id',
             'foreign' => 'tool_id'));

        $this->hasMany('ProjectTool as ProjectTools', array(
             'local' => 'id',
             'foreign' => 'project_id'));
    }
}