<?php

/**
 * BaseProjectTool
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $project_id
 * @property integer $tool_id
 * @property Tool $Tool
 * @property Project $Project
 * 
 * @method integer     getProjectId()  Returns the current record's "project_id" value
 * @method integer     getToolId()     Returns the current record's "tool_id" value
 * @method Tool        getTool()       Returns the current record's "Tool" value
 * @method Project     getProject()    Returns the current record's "Project" value
 * @method ProjectTool setProjectId()  Sets the current record's "project_id" value
 * @method ProjectTool setToolId()     Sets the current record's "tool_id" value
 * @method ProjectTool setTool()       Sets the current record's "Tool" value
 * @method ProjectTool setProject()    Sets the current record's "Project" value
 * 
 * @package    sitioCalidad
 * @subpackage model
 * @author     Fernando G. Panci
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProjectTool extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('project_tool');
        $this->hasColumn('project_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('tool_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Tool', array(
             'local' => 'tool_id',
             'foreign' => 'id'));

        $this->hasOne('Project', array(
             'local' => 'project_id',
             'foreign' => 'id'));
    }
}