<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/03/28 19:55:07

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=bbddCalidad',
  'username' => 'root',
  'password' => '31fer405',
  'name' => 'doctrine',
)),);
