<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/03/18 15:27:01
sfConfig::add(array(
  'mod_sfguardpermission_enabled' => true,
  'mod_sfguardpermission_view_class' => 'sfPHP',
));
