<?php

/**
 * ProjectToolTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProjectToolTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProjectToolTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProjectTool');
    }
}