<?php

/**
 * Tool
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sitioCalidad
 * @subpackage model
 * @author     Fernando G. Panci
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Tool extends BaseTool
{
  public function __toString()
  {
    return $this->getName();
  }
}
