<?php

/**
 * ToolTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ToolTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ToolTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Tool');
    }
}