application:
  class: sfDoctrineRouteCollection
  options:
    model:                Application
    module:               solicitud
    prefix_path:          /solicitud
    column:               id
    with_wildcard_routes: true

guide:
  class: sfDoctrineRouteCollection
  options:
    model:                Guide
    module:               guia
    prefix_path:          /guia
    column:               id
    with_wildcard_routes: true

tool:
  class: sfDoctrineRouteCollection
  options:
    model:                Tool
    module:               herramienta
    prefix_path:          /herramienta
    column:               id
    with_wildcard_routes: true

company_empresa:
  class: sfDoctrineRouteCollection
  options:
    model:                Company
    module:               empresa
    prefix_path:          /empresa
    column:               id
    with_wildcard_routes: true

company:
  class: sfDoctrineRouteCollection
  options:
    model:                Company
    module:               company
    prefix_path:          /company
    column:               id
    with_wildcard_routes: true

# default rules
homepage:
  url:   /
  param: { module: main, action: index }

sf_guard_signin:
  url:   /login
  param: { module: sfGuardAuth, action: signin }

sf_guard_signout:
  url:   /logout
  param: { module: sfGuardAuth, action: signout }

sf_guard_password:
  url:   /request_password
  param: { module: sfGuardAuth, action: password }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
