generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Company
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              Company
    plural:                Companies
    route_prefix:          company_empresa
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions:
        _new:               { label: "Nueva Empresa" }
      fields:  
        name:               { label: "Nombre"}
        is_active:          { label: "Activa"}
        country_id:         { label: "País" }
        country_name:       { label: "País" }
      list:
        title:              Empresas
        batch_actions:      {}
        display:            [name, is_active, country_name]
        #peer_method:        doSelectJoinCompanyCountry
      filter:  ~
      form:    ~
      edit:    
        title:              Editar Empresa
      new:     
        title:              Nueva Empresa
