generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Company
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              Company
    plural:                Companies
    route_prefix:          company_empresa
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions:
        _new:              { label: "Nueva Empresa" }
      fields:  ~
      list:    ~
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
