generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Guide
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          guide
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: 
        _new:              { label: "Nueva Guía" }
      fields:  
        code:              { label: "Código", help: "código externo" }
        url:               { help: "http://www.faqs.org/rfcs/rfc821.html" }
        name:              { label: "Nombre" }
        description:       { label: "Descripción" }
        tool_id:           { label: "Herramienta" }
        tool_name:         { label: "Herramienta" }
      list:
        title:             Guías
        batch_actions:     {}
        #peer_method:       doSelectJoinTool   <-no anda
        display:           [code, url, name, description, tool_name ]
      filter:
        display:           [code, name, tool_id]
      form:    ~
      edit:
        title:             Editar Guía
      new:
        title:             Nueva Guía
