generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Application
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          application
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions:
        _new:              { label: "nueva solicitud" }
      fields:
        name:              { label: "Nombre" }
        state:             { label: "Estado" }
        description:       { label: "Descripcion" }
        company_id:        { label: "Empresa" }
        company_name:      { label: "Empresa" }
      list:
        title:             Solicitudes
        batch_actions:     {}
        display:           [name, state, description, company_name]
      filter:
        display:           [name, state, company_id]
      form:    ~
      edit:
        title:             "Editar Solicitud"
      new:
        title:             "Nueva solicitud"
