Country:
  columns:
    id: { type: integer(4), autoincrement: true, primary: true }
    name: { type: string(255), notnull:true, unique: true }

Company:
  columns:
    id: { type: integer(4), autoincrement: true, primary: true }
    name: { type: string(255), notnull:true, unique: true }
    is_active: { type: boolean, notnull: true, default: 0 }
    country_id: { type: integer(4) }
  relations:
    Country:
      foreignAlias: Companys

Application:
  columns:
    id: { type: integer(4), autoincrement: true, primary: true }
    name: { type: string(255), notnull:true, unique: true }
    state:
      type: enum
      values: [pendiente, aprobada, desaprobada]
    description: blob
    company_id: { type: integer(4) }
  relations:
    Company:
      foreignType: one

Project:
  columns:
    id: { type: integer(4), autoincrement: true, primary: true }
    name: { type: string(255), notnull:true, unique: true }
    url: { type: string(255) }#                                             ver
    description: blob
    company_id: integer(4)
  relations:
    Company:
      foreignAlias: Projects
    Tools:
      foreignAlias: Projects
      class: Tool
      refClass: ProjectTool

Tool:
  columns:
    id: { type: integer(4), autoincrement: true, primary: true }
    code: { type: string(255), notnull:true, unique: true }
    name: { type: string(255), notnull:true, unique: true }
    url: { type: string(255) }
    description: blob

ProjectTool:
  columns:
    project_id: { type: integer(4), primary: true }
    tool_id: { type: integer(4), primary: true }
  relations:
    Tool:
      foreignAlias: ProjectTools
    Project:
      foreignAlias: ProjectTools

Guide:
  columns:
    id: { type: integer(4), autoincrement: true, primary: true }
    code: { type: string(255), notnull:true, unique: true }
    name: { type: string(255), notnull:true, unique: true }
    url: { type: string(255), notnull:true }
    description: blob
    tool_id: integer (4)
  relations:
    Tool:
      foreignType: one