generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Tool
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          tool
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: 
        _new:              { label: "Nueva Herramienta"}
      fields:
        code:              { label: "Código", help: "código externo" }
        name:              { label: "Nombre" }
        url:               { help: "www.google.com/imagenes" }
        description:       { label: "Descripción" }
        projects_list:     { label: "Proyectos" }
      list:    
        title:             Herramientas
        batch_actions:     {}
        display:           [code, name, url, description]
      filter:  
        display:           [code, name]
      form:
        display:
          NONE:            [code, name, url, description]
      edit:    
        title:             "Editando herramienta: %%name%%"
      new:     
        title:             Nueva Herramienta
